// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gremltqbvlcvxlsyzenr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZW1sdHFidmxjdnhsc3l6ZW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjY4OTgsImV4cCI6MjA2NzkwMjg5OH0.keb9NhD2x1pxhKVA6zOATbPiwRx7a2jeKk5IkOqO-jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});